
service: type-recogniser
app: type-recogniser
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  #  stage: dev
  region: eu-central-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  artifact: build/distributions/type-recogniser.zip

functions:
  type-recogniser:
    handler: com.vilkas.aws.accounting.LambdaHandler
    name: type-recogniser
    events:
      - s3:
          bucket: vilius-accounting-demo-bucket
          event: s3:ObjectCreated:*
          existing: true


